development:
  adapter: postgresql
  encoding: unicode
  database: rails_rumble_2013_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: rails_rumble_2013_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: railsrumble_production
  username: "www-data"
  password: "f12a1db00639882d56063fc6f73582ef"
