development:
  adapter: postgresql
  encoding: unicode
  database: rails_rumble_2013_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: rails_rumble_2013_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: kaylas_tour_production
  username: db
  password: aac059a3c09cfd1521d5b8525b2ebd7a
